version: '3'
services:
  cypress:
    image: cypress/browsers:node16.5.0-chrome94-ff93
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - ./docker-data/db-data:/data/db
    ports:
      - 27017:27017
volumes:
  db-data:
