version: '3'
services:
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - ./docker-data/db-data:/data/db
    ports:
      - ${DOCKER_MONGO_PORT}:27017
  mongo-express:
    image: mongo-express:0.54
    restart: always
    depends_on:
      - mongo
    ports:
      - ${DOCKER_ADMIN_PANEL_PORT}:8081
volumes:
  db-data:
