#! /bin/bash

cat <<< "# CLIENT
BASE_URL = ${BASE_URL}
CLIENT_URL = ${CLIENT_URL}
CLIENT_PORT = ${CLIENT_PORT}
DEVTOOLS_ENABLED = ${DEVTOOLS_ENABLED}

# SERVER
SERVER_URL = ${SERVER_URL}
PORT = ${PORT}
DB_URL = ${DB_URL}
LOGGER_ENABLED = ${LOGGER_ENABLED}
RATE_LIMIT_ENABLED = ${RATE_LIMIT_ENABLED}
RATE_LIMIT = ${RATE_LIMIT}

# DOCKER
DOCKER_MONGO_PORT = ${DOCKER_MONGO_PORT}
DOCKER_ADMIN_PANEL_PORT = ${DOCKER_ADMIN_PANEL_PORT}

# TOKENS
ACCESS_TOKEN_SECRET = ${ACCESS_TOKEN_SECRET}
REFRESH_TOKEN_SECRET = ${REFRESH_TOKEN_SECRET}
DOCS_TOKEN_SECRET = ${DOCS_TOKEN_SECRET}

# DOCS
DOCS_PASSWORD = ${DOCS_PASSWORD}

# ADMIN
ADMIN_USERNAME = ${ADMIN_USERNAME}
ADMIN_PASSWORD = ${ADMIN_PASSWORD}
ADMIN_EMAIL = ${ADMIN_EMAIL}

# OTHERS
APP_ENV = ${APP_ENV}
NODE_ENV = ${NODE_ENV}

# SENTRY
SENTRY_FRONTEND_ENABLED = ${SENTRY_FRONTEND_ENABLED}
SENTRY_FRONTEND_DSN = ${SENTRY_FRONTEND_DSN}
SENTRY_FRONTEND_AUTH_TOKEN = ${SENTRY_FRONTEND_AUTH_TOKEN}
SENTRY_FRONTEND_ORGANIZATION_NAME = ${SENTRY_FRONTEND_ORGANIZATION_NAME}
SENTRY_FRONTEND_PROJECT_NAME = ${SENTRY_FRONTEND_PROJECT_NAME}" > .env
