services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/react-blog:cached
    command: sleep infinity
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      - mongodb
