export default {
  GLOBAL_ERRORS: {
    CONFLICT_ERROR: 'CONFLICT_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    NOT_FOUND_URL_ERROR: 'NOT_FOUND_URL_ERROR',
    UNAUTHORIZED_ERROR: 'UNAUTHORIZED_ERROR',
    FORBIDDEN_ERROR: 'FORBIDDEN_ERROR',
    BAD_REQUEST_ERROR: 'BAD_REQUEST_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  },

  TOKEN_ERRORS: {
    INVALID_REFRESH_TOKEN_ERROR: 'INVALID_REFRESH_TOKEN_ERROR',
    INVALID_CSRF_TOKEN_ERROR: 'INVALID_CSRF_TOKEN_ERROR',
  },

  VALIDATION_ERRORS: {
    BODY_VALIDATION_ERROR: 'BODY_VALIDATION_ERROR',
    PARAMS_VALIDATION_ERROR: 'PARAMS_VALIDATION_ERROR',
    QUERY_VALIDATION_ERROR: 'QUERY_VALIDATION_ERROR',
  },

  PERMISSION_ERRORS: {
    PERMISSION_REQUIRED_ERROR: 'PERMISSION_REQUIRED_ERROR',
    PERMISSION_NOT_EXIST_ERROR: 'PERMISSION_NOT_EXIST_ERROR',
  },

  AUTH_ERRORS: {
    CANNOT_BE_LOGGED_IN_ERROR: 'CANNOT_BE_LOGGED_IN_ERROR',
  },

  DOCS_ERRORS: {
    OPTION_DISABLED_ERROR: 'OPTION_DISABLED_ERROR',
    PASSWORD_NOT_CORRECT_ERROR: 'PASSWORD_NOT_CORRECT_ERROR',
    CONFIGURATION_NOT_FOUND_ERROR: 'CONFIGURATION_NOT_FOUND_ERROR',
  },

  ABOUT_ERRORS: {
    ABOUT_NOT_FOUND_ERROR: 'ABOUT_NOT_FOUND_ERROR',
    ABOUT_NOT_UPDATED_ERROR: 'ABOUT_NOT_UPDATED_ERROR',
  },

  CONTACT_ERRORS: {
    CONTACT_NOT_FOUND_ERROR: 'CONTACT_NOT_FOUND_ERROR',
    CONTACT_NOT_UPDATED_ERROR: 'CONTACT_NOT_UPDATED_ERROR',
  },

  CONFIG_ERRORS: {
    CONFIG_NOT_FOUND_ERROR: 'CONFIG_NOT_FOUND_ERROR',
    CONFIG_NOT_UPDATED_ERROR: 'CONFIG_NOT_UPDATED_ERROR',
  },

  USER_ERRORS: {
    USER_NOT_FOUND_ERROR: 'USER_NOT_FOUND_ERROR',
    USER_NOT_CREATED_ERROR: 'USER_NOT_CREATED_ERROR',
    EMAIL_ALREADY_EXIST_ERROR: 'EMAIL_ALREADY_EXIST_ERROR',
    USERNAME_ALREADY_EXIST_ERROR: 'USERNAME_ALREADY_EXIST_ERROR',
    PASSWORD_NOT_CORRECT_ERROR: 'PASSWORD_NOT_CORRECT_ERROR',
  },

  TERMS_OF_USE_ERRORS: {
    TERMS_OF_USE_NOT_FOUND_ERROR: 'TERMS_OF_USE_NOT_FOUND_ERROR',
    TERMS_OF_USE_NOT_UPDATED_ERROR: 'TERMS_OF_USE_NOT_UPDATED_ERROR',
  },

  ROLE_ERRORS: {
    ROLE_NOT_FOUND_ERROR: 'ROLE_NOT_FOUND_ERROR',
    ROLE_ALREADY_EXIST_ERROR: 'ROLE_ALREADY_EXIST_ERROR',
    ROLE_CANNOT_BE_CHANGED_ERROR: 'ROLE_CANNOT_BE_CHANGED_ERROR',
    ROLE_CANNOT_BE_DELETED_ERROR: 'ROLE_CANNOT_BE_DELETED_ERROR',
    ROLE_NOT_CREATED_ERROR: 'ROLE_NOT_CREATED_ERROR',
    ROLE_NOT_UPDATED_ERROR: 'ROLE_NOT_UPDATED_ERROR',
    ROLE_NOT_DELETED_ERROR: 'ROLE_NOT_DELETED_ERROR',
    ROLES_NOT_FOUND_ERROR: 'ROLES_NOT_FOUND_ERROR',
    ROLES_NOT_DELETED_ERROR: 'ROLES_NOT_DELETED_ERROR',
  },

  FAQ_ERRORS: {
    FAQ_NOT_FOUND_ERROR: 'FAQ_NOT_FOUND_ERROR',
    FAQ_ALREADY_EXIST_ERROR: 'FAQ_ALREADY_EXIST_ERROR',
    FAQ_NOT_CREATED_ERROR: 'FAQ_NOT_CREATED_ERROR',
    FAQ_NOT_UPDATED_ERROR: 'FAQ_NOT_UPDATED_ERROR',
    FAQ_NOT_DELETED_ERROR: 'FAQ_NOT_DELETED_ERROR',
    FAQS_NOT_FOUND_ERROR: 'FAQS_NOT_FOUND_ERROR',
    FAQS_NOT_DELETED_ERROR: 'FAQS_NOT_DELETED_ERROR',
  },

  MESSAGE_ERRORS: {
    MESSAGE_NOT_FOUND_ERROR: 'MESSAGE_NOT_FOUND_ERROR',
    MESSAGE_NOT_CREATED_ERROR: 'MESSAGE_NOT_CREATED_ERROR',
    MESSAGE_NOT_UPDATED_ERROR: 'MESSAGE_NOT_UPDATED_ERROR',
    MESSAGE_NOT_DELETED_ERROR: 'MESSAGE_NOT_DELETED_ERROR',
    MESSAGES_NOT_FOUND_ERROR: 'MESSAGES_NOT_FOUND_ERROR',
    MESSAGES_NOT_DELETED_ERROR: 'MESSAGES_NOT_DELETED_ERROR',
  },
};
